### ISSUE TITLE
Getting `Uncaught (in promise) ReferenceError: process is not defined`

### ISSUE THREAD

**Issue by mohdmusthafaneo** [yahilo/yah-js-sdk#9]
Getting `Uncaught (in promise) ReferenceError: process is not defined`
![image](https://user-images.githubusercontent.com/121943295/215687022-948308fc-c650-48ae-bdf0-7e511629a7fb.png)

The error is thrown from this line. Commenting this code and statically setting the `const authorizationEndpoint = 'https://shield.appblocks.com/'`solves this issue
![image](https://user-images.githubusercontent.com/121943295/215686716-fb5d385f-6df6-4e8a-89f0-6d750dfd219c.png)
![image](https://user-images.githubusercontent.com/121943295/215688233-7cc49f1f-b022-43ca-896f-5554541d350b.png)

**Need this fix in the published version. Thank you**

**Comment by frederic-neo** [comment]
Please make the following changes in the webpack config.
```
plugins: [
    new DefinePlugin({
      process: { env: JSON.stringify(Dotenv.parsed) },
    }),
```

hope this solves the issue.

**Comment by mohdmusthafaneo** [comment]
OK THAT WORKS!! 😄

**Comment by mohdmusthafaneo** [comment]
It would be great if this fix is also in the CLI generated webpack configuration

**Comment by frederic-neo** [comment]
sure will implement it , also looking for a alternate fix
